tap_install:
    sensitive_values:
        shared:
            image_registry:
                project_path: ENC[AES256_GCM,data:4vHTByD3auHmsEJ5/Qrf9/REKdlRjprak2rLlbRVwqAmPkN3TqQ0CQ==,iv:DBGy7G61jeyFHFNYuln898NK0qNqFJMu2L0TdWk4Mqo=,tag:prVsUX4F3IFZSWQWLhp8uA==,type:str]
                username: ENC[AES256_GCM,data:j+gfg5q46lWn,iv:wCrRQ6p5dlGRsLaXVL0cKzLlOtIGS3Zt5ciSqF8bcds=,tag:OxP8XnJviTINgqhAOVD/jw==,type:str]
                password: ENC[AES256_GCM,data:1c8nezDA2LiSCh5McaX7pK5GzdQmIz6iMhHfPquoG8ZRwPYhTk9q5jE3RnQHtT+bhUkxmw==,iv:TxgS0CaGEpwB7wqvq9XN7fzmli1sQPptZ8ATZzEmS6I=,tag:er4CyJ0x98GY6A5bk+Dgnw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ru76hw3um80tmuasmuvzm4ql0clrhp8y7mjqtq2ljnm9la0glqvss5efxy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIOG5OUzFPT2JpT0VLemh4
            U28wMzFXM1orN2lpSjQyR05mUjhjQ1dnZzBrClc2OThyOENYNlh3V1ZiR0xJanJ4
            V2tWUVBvWGR4L29Jdy84TTBUMWU2dkkKLS0tIDMvMzF5UU9STVNqa1lOM2k4OGx3
            aDY2WkxiUDRKZjRQTWxHY29hbEI5SHcKNG6KIzB7vS4HpgTYfTITu3vkpTinc6Fz
            PBaTilxGtMQQU/4uIAyB5WdDPE3wsumf/WJsYRS/k7Vf2AH3D5Fjnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-23T17:21:33Z"
    mac: ENC[AES256_GCM,data:KNpfoKmrTw5WgCqqY1BKSOtEjD6VHQnBzefbMUzkfcMyzf6HEtSnAGgUKboSQJ8dW2Cec4JvTnwRkt3HQmDwlX3xl849pdJNZOwGnZO1Gy8u5WBiKPBi7am+Q3/Hdy2BgDFmTILsR39nZMD0QmR7S71xN8YdI5as6T+lZR7oM3E=,iv:D30kQ/RNCj5olLyFaMGOF6zOcuto6WOMv1ZoQcLf/pc=,tag:M1Jz+UsUgvXM8dYG0nSoXw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
