tap_install:
    sensitive_values:
        shared:
            image_registry:
                project_path: ENC[AES256_GCM,data:QT7E0BctIao0sd8MABiwT4zQwedZWzyvahFXx0syMPhv,iv:LkWSnPIvR75FvHLHnxyZy+yHZ5ebhkiTkScP87/Jk08=,tag:ARZ2ZteB8IQWCCtjS9kO3Q==,type:str]
                username: ENC[AES256_GCM,data:fy/67BXwRfkM,iv:OcmyLR2MVuruigYW/O1lgnp3UkrlhQswjVrLvPkuj9k=,tag:OQAgzjMmA0G1WhrqwtAydA==,type:str]
                auth: ENC[AES256_GCM,data:/HGQhztXm0qaZ2ILLlxvYT9nWViI7qGtuJIi1fU5QH9N4HmcrMGo2qMS7MGZLIYER9zZaQ==,iv:gZ6fFgT3NawQ7Pm5lf7pd0WrxPxPuHMWJ8mpmvpHC1A=,tag:2U7yu8V3vndC8idCn64rZw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ru76hw3um80tmuasmuvzm4ql0clrhp8y7mjqtq2ljnm9la0glqvss5efxy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzTDVVaVUrZlJJSUJ5NFhF
            bFN5cmRyRlU0YTEzcWFXc1hCK0dTaW00T0RvCmVwaStnUDhrWnhtYTM2blZLdkRi
            RlpDZytKN3h4STBoNVZzUXVyV3BuQkkKLS0tIG14ZDVEV1JUczVvSmhxdU02ME44
            Unk0c2tZSmV2RmFTQkE1bldiWERmMEkKvAl5HmyQMTfJSABFdlAofv1jFse/rRpC
            Rkj9hlUO6a4ATGbjFuIVT9THc14byu02aEN0QS/tfo2w5VFexwjU0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-30T12:01:12Z"
    mac: ENC[AES256_GCM,data:cmRdB17Q2KVnplAaTRgk3zLfTguMbaLeD1LAhQoSshDsQfuPCVvOpiFg7z1GIJJjHynXMP1i9pPY4OZKQl3Qa1E2OASp7e25qR+wd9vyHtC+SGGZT8VkaANhHzPfqk/OR32J9G9F2dfzoKp8hPrQfTpgayJf5ydqIM16V9RY+7U=,iv:pUVtfGcFT7RVT1hfCPjGZtHO6fDPJjZs13vFcE5TPMM=,tag:wSxlC9fY8vqy77uYbQr1mw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
